#!/bin/sh

terminal=st

mat=$( find ~/.cuadernos/* -maxdepth 1 -type d -printf '%f\n' | rofi -dmenu -theme oxide)

if [ "$mat" != "" ]
then

	if [ "$1" = "-v" ] # abrir cuadernos viejos
	then

		opc=$(find ~/.cuadernos/"$mat"/* -name '*.xopp' -printf '%f\n'  | rofi -dmenu -theme oxide )

		if [ "$opc" != "" ]
		then
			aplicacion=xournalpp
			nom=~/.cuadernos/"$mat/$opc"
			echo "abriendo $nom"
		fi

	elif [ "$1" = "-vt" ] # abrir cuadernos viejos
	then
		opc=$(find ~/.cuadernos/"$mat"/* -printf '%f\n' | rofi -dmenu -theme oxide )

		if [ "$opc" != "" ]
		then
			aplicacion="$terminal -e $EDITOR"
			nom=~/.cuadernos/"$mat/$opc"
			echo "abriendo $nom"
		fi


	elif [ "$1" = "-p" ] # abrir un cuaderno de practica
	then # aun no sirve

		nom=~/.cuadernos/"$mat/$mat-practica"
		# aqui me gustaria que siempre fuera al mismo archivo, y crearlo si no existe
		echo "creando $nom"

	else

		nom=~/.cuadernos/"$mat/$mat-$(date +%F-%R)"
		if [ "$1" = "-t" ] # abre un archivo de texto con un editor de texto
		then

		    nom=~/.cuadernos/"$mat/$mat-$(date +%F)"
			echo "creando $nom"
			aplicacion="$terminal -e $EDITOR"

		elif [ "$1" = "-x" ] # abre un archivo con xournalpp
		then
			echo "creando $nom"
			aplicacion=xournalpp
			ext=.xopp
			cp ~/.cuadernos/.default/default.xopp "$nom$ext"

		else
			echo "opcion invalida, pobre opcion"
		fi
	fi

	# echo "$aplicacion $nom$ext"

	if [ "$nom" != "" ] # abre el cuaderno
	then
		( eval "$aplicacion $nom$ext" &> /dev/null & )
	fi

fi
