#!/bin/sh

# alias

alias pila="upower -d"
alias llaves="gpg --list-secret-keys --keyid-format LONG"
alias pantalla=arandr
alias clima="curl wttr.in"

alias duck="mono ~/.steam/steam/steamapps/common/Duck\ Game/DuckGame.exe"

# sistema

# mostrar todos los archivos de la carpeta, organizados por peso
alias peso='du -shx ./{*,.*} | sort -rh'
alias cont='cd $(continuar)'

# git
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias gis='git status'
alias gco='git checkout'

alias config-add='cd ~ ; config add $( cat ~/.cfg-add ); cd -; config status'

alias ssh='eval `keychain --eval --agents ssh ~/.ssh/id_rsa`; ssh'

upd_pacman()
{
    sudo pacman -Syu
    printf "\n\n Terminada actualización pacman \n\n\n"

    [ "$(command -v yay)" != "" ] && yay -Syu &&
        printf "\n\n Terminada actualización aur \n\n"

    purgetheorphans
}

upd_ubuntu()
{
    sudo apt update
    sudo apt upgrade --fix-missing
    sudo apt dist-upgrade
    sudo apt autoremove
}

upd()
{
    if [ "$(command -v pacman)" != "" ]; then
        echo "actualizando Arch"
        upd_pacman
    elif [ "$(command -v apt)" != "" ]; then
        echo "actualizando Debian"
        upd_ubuntu
    fi
}

# this or that: usar la primera opcion en caso de ser posible, de lo contrario
# usar la segunda
_t_o_t()
{
    echo "TODO"
}

alias cd=" cd" # no es necesario que cada cd aparezca en historia
# alias ls=" ls"
# alias ls=" exa"
# alias ls="
#     if lsd 2>/dev/null; then
#         command 'lsd '
#     else
#         command 'ls '
#     fi"
alias l=" exa -l"
alias sudo='sudo ' # pa los alias
alias rf=' rm -rf'

# alias iwannadai="rm -rf /"
# alias russian="[ $[ $RANDOM % 6 ] = 0 ] && echo 'bang' || echo 'Lucky boi' "

alias showshs="cat /etc/shells" # mostrar todos los shells disponibles
alias changesh='echo $SHELL;showshs;chsh;sudo shutdown -r 0' # cambiar el shell
alias se='ls /usr/bin | grep'

alias usb='cd /run/media/dhas'
alias clear='clear ; [[ ! -z "$TMUX" ]] && tmux clear-history ' # limpiar la pantalla y el historial de tmux

# para siempre comenzar en init, evitando estar creando nuevas sesiones constantemente
# alias tmux="tmux new -A -s Init"

alias matar=pkill
alias word='grep -rnw . -e '
alias open='xdg-open' # abrir archivos con el programa predeterminado

alias practical='nvim -u ~/.vimrc'

# git
alias gis='git status'
alias gca='git commit -a'
alias gco='git checkout'

# evitar abrir vim dentro de vim
open_vim()
{
    if [ -z "$VIMRUNTIME" ]
    then
        nvim $@
    else
        echo ":v"
        for val in $@
        do
            echo "$val"
        done
    fi
}

# alias e='TERM=xterm-256color emacs'
alias e='TERM=xterm-256color emacsclient -nw'
alias em='TERM=xterm-256color emacs -nw'
alias v=' open_vim'
alias vim=' open_vim'
alias sv='sudo nvim'
alias vall=' open_vim $(find . -type f)'
alias viz=' open_vim $(fzf)'
# tmux
alias tkill='tmux kill-session'

# scripts
alias goto=". goto"

# web
alias whats='xdg-open https://web.whatsapp.com/'
alias yt=youtube
alias opgit="xdg-open https://github.com/dhasane"
alias dmusic='youtube-dl --extract-audio -i --audio-format mp3 ' # aqui va el link  # descargar musica

# lenguajes

# construir con make
alias mk=make
alias db='
	if [ ! -d build ]
		then
			echo "carpeta creada"
			mkdir build
		fi;
	cd build;
	cmake ..
	'

alias rb='
	if [ -d build ]
		then
			rm -rf build
			echo "carpeta build eliminada"
		else
			echo "carpeta build inexistente"
		fi;
	'

alias dmk='
	if [ ! -d build ]
		then
			echo "carpeta creada"
			mkdir build
		fi;
	cd build;
	cmake ..;
	make;
	cd ..;
	'

# lenguajes
alias py=python3
alias py2=python2
alias prolog=swipl
alias rr=Rscript
alias jav=javac

###########
# funciones
###########

# subir directorios como : .. # , donde # es el numero de directorios a subir
..() {
    cd $(for ((c=0; c<${1:-1}; ++c)); do echo -n ../; done) || exit
}
alias ..=" .."

# eliminar paquetes huerfanos
# alias purgetheorphans='sudo pacman -Rns $(pacman -Qtdq)'
# para que no salgan errores innecesarios al
# no haber paquetes para eliminar
purgetheorphans() {
    brr=$(pacman -Qtdq)
    # echo "\"$brr\""
    if [ "$brr" != "" ]; then
        echo " Eliminando: "
        sudo pacman -Rns $(pacman -Qtdq)
    else
        echo " No hay paquetes para limpiar"
    fi
}

# Find files with extension
# Usage: fext <ext> [max_depth]
fext() {
  if [ -z "${2}" ]; then
    find . -type f -name "*.${1}"
  else
    find . -maxdepth "${2}" -type f -name "*.${1}"
  fi
}

# Find file/directory by substring
# Usage: fn <substring> [max_depth]
fn() {
  if [ -z "${2}" ]; then
    find . -iname "*${1}*"
  else
    find . -maxdepth "${2}" -iname "*${1}*"
  fi
}

