#!/bin/sh

MAC="00:18:09:A2:DC:0D"

connect()
{
    rep=0
	ret="inicio"
	while [ -n "$ret" ]
	do
        rep=$((rep+1))
        ret=$(bluetoothctl connect "$MAC" | grep Fail)
	done
    echo "connected after $rep attempts"
}

if [ -z "$1" ]
then
    printf "\t options\n"
    printf "\t [c]onnect \n"
    printf "\t [r]e connect \n"
    printf "\t [d]isconnect \n"
    printf "\t change [m]ac \n"

else
    while getopts m:crd option
    do
        if [ "$option" = "m" ];then
            MAC=$OPTARG
        fi
        if [ "$option" = "d" ] || [ "$option" = "r" ]; then
            sudo rfkill block bluetooth
            bluetoothctl discoverable off
        fi
        if [ "$option" = "r" ] || [ "$option" = "c" ] || [ "$option" = "m" ]; then
            bluetoothctl discoverable on
            sudo rfkill unblock bluetooth
            connect
            bluetoothctl discoverable off
        fi
    done
fi
