#!/bin/sh

CONTINUAR="$HOME/.continuar"

if [ -z "$1" ]
then
    ubi=$(command cat "$CONTINUAR" | fzf)
    cd "$ubi" || return
else
    while getopts gv option
    do
        case "${option}"
        in
        v)
            cat "$CONTINUAR"
            ;;
        g)
            ubicacion=$(pwd)
            echo "guardando $ubicacion, para continuar mas tarde"
            echo "$ubicacion" >> "$CONTINUAR"
            ;;
        *)
            exit
            ;;
        esac
    done
fi
