#!/bin/sh

terminal=st
TERMINAL="$terminal -e $EDITOR"
EXTT=".md"
VISUAL=xournalpp
EXTV=.xopp

# 1 -> aplicacion ; 2 -> nombre
abrir ()
{
	if [ "$2" != "" ] # abre el cuaderno
	then
		( eval "$1 $2" &> /dev/null & )
		# ( eval "$aplicacion $nom$ext" &> /dev/null & )
	fi
}

viejos()
{
    # opc=$(find "$ubicacion/$mat"/* -name '*.xopp' -printf '%f\n'  | rofi -dmenu -theme oxide )
    opc=$(find "$ubicacion"/"$mat"/* -printf '%f\n' | rofi -dmenu -theme oxide )

    if [ "$opc" != "" ]
    then
        case "$opc"
            in
            *".xopp"*)
                aplicacion=$VISUAL
                ;;
            *)
                aplicacion=$TERMINAL
                ;;
        esac

        nom="$ubicacion/$mat/$opc"

        abrir "$aplicacion" "$nom"
    fi
}

if [ -z "$1" ]
then

    printf "las posibles opciones son las siguientes: \n"
    printf "\tcrear nueva carpeta\t-n\n"
    printf "\tarchivos viejos \t-v\n"
    printf "\tarchivo de texto\t-t\n"
    printf "\tarchivo grafico \t-x\n"
else
    ubicacion="$HOME/repos/cuadernos"
    mat=$( find "$ubicacion"/* -maxdepth 1 -type d -printf '%f\n' | rofi -dmenu -theme oxide)
fi

if [ "$mat" != "" ]
then

	nom="$ubicacion/$mat/$mat-$(date +%F)"
    while getopts vtxn option
    do
        case "${option}"
        in
            v)
                viejos
                ;;
            n)
                mkdir "$ubicacion/$mat"
                ;;
            t)
                aplicacion=$TERMINAL
                ext=$EXTT
                abrir "$aplicacion" "$nom$ext"
                ;;
            x)
                aplicacion=$VISUAL
                ext=$EXTV
                if ! [ -f "$nom$ext" ]; then
                    cp "$ubicacion"/.default/default.xopp "$nom$ext"
                fi
                abrir "$aplicacion" "$nom$ext"
                ;;
            *)
                exit
                ;;
        esac
    done
fi
