#!/bin/sh

LIBROS="$HOME/MEGA/actual/"
lib="$(find "$LIBROS"/* -maxdepth 0 -type f -printf '%f\n' | rofi -dmenu -theme oxide )"

if [ "" != "$lib" ]; then
    ( xdg-open "$LIBROS/$lib" &> /dev/null & )
fi


