#!/bin/sh

ids=$(xinput list | sed "/pointer/s/[[:space:]]\+/\n/g;t;d" | sed "/id=/s/id=//g;t;d")

dir="0 0 0 0 0 0 0 0 0"
xrandr -o 0
while getopts r option
do
    case "${option}"
    in
    r)
        dir="0 -1 1 1 0 0 0 0 1"
        xrandr -o 1
        ;;
    *)
        exit
        ;;
    esac
done
# if [ "$1" = "-r" ]
# then
#     dir="0 -1 1 1 0 0 0 0 1"
#     xrandr -o 1
# else
#     dir="0 0 0 0 0 0 0 0 0"
#     xrandr -o 0
# fi

#echo "$dir"

for id in $ids
do
	#echo "$id"
	xinput set-prop "$id" --type=float "Coordinate Transformation Matrix" $dir
done

