#!/bin/sh

dir=.
while getopts l:h option
do
    case "${option}"
    in
    l) # location
        dir="${OPTARG}"
        ;;
    h) # home
        dir=~
        ;;
    *)
        exit
        ;;
    esac
done

val=$( find "$dir" -type f | fzf )

if [ "$val" != "" ]
then
    echo "abriendo :$val"
    $EDITOR "$val"
fi

