#!/usr/bin/sh

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    eww daemon
    sleep 1
fi

## Open widgets
run_eww() {
    eww open-many \
        barCenter \
        user \
        power \
        date \
        control \
        system \
        fetch \
        player \
        home \
        disk \
        downloads \
        pictures \
        documents \
        favourite
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
    touch "$FILE"
    run_eww
else
    eww close-all
    rm "$FILE"
fi
